version: "3.3"

services:
  web:
    build: .
    image: django
    container_name: recon_web
    command: sh -c "apt-get update && pip install -r requirements.txt && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - .env
    volumes:
      - ./:/recon
    ports:
      - 8000:8000
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
